### ISSUE TITLE
Ícono de "Presentación" del Sidebar

### ISSUE THREAD

**Issue by ornemosc** [10PinesLabs/ruth#26]
No tiene el ícono correspondiente al mock-up porque la diseñadora lo creó a mano en vez de obtener alguno de fontawasome (porque los que hay, hay que pagarlos).
Se deberá ver cómo lo solucionamos o como podemos hacer fácil lo de cambiar el color a un .SVG

**Comment by jazcarate** [comment]
En qué quedó esto?
En producción veo 3 iconos bonitos que cambian de color

**Comment by ornemosc** [comment]
Jess nos dijo que el que pusimos para presentación estaba bueno, y que no tiene problema en que quede ese. Cierro el issue.
