### ISSUE TITLE
Heroku no permite la navegación mediante URL

### ISSUE THREAD

**Issue by fgmf94** [10PinesLabs/ruth#67]
En heroku cuando se ingresa a la URL: /reunionDeRoots aparece el mensaje Not Found, en cambio debería redirigir ya sea a la vista de tema actual o iniciar reunión de acuerdo a si se encuentra abierta o cerrada la reunión.

El problema también se puede visualizar en /mobile y /oradores.

Posible solución:
https://stackoverflow.com/questions/41772411/react-routing-works-in-local-machine-but-not-heroku

**Comment by ludat** [comment]
deprecadisimo
