### ISSUE TITLE
Revisar cómo estamos inyectando dependencias

### ISSUE THREAD

**Issue by fgmf94** [10PinesLabs/ruth#9]
¿Queremos inyectar objetos gordos? ¿Queremos solamente métodos (lo que estamos haciendo)?
¿Queremos encontrar otra forma de hacerlo?

**Comment by jazcarate** [comment]
Creo que el patrón que quedó donde `routes` tiene la llamada al controller, y el controller deconstruye el `contex` que necesita vá bien. Voy a cerrarlo :)
